### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by SQWung** [nayan-pradhan/solo-6dof-motion-platform#1]
```
Traceback (most recent call last):
  File "~\solo-6dof-motion-platform\src\start_program.py", line 322, in <module>
    StartProgramClass()
  File "~\solo-6dof-motion-platform\src\start_program.py", line 48, in __init__
    self.get_user_input()
  File "~\solo-6dof-motion-platform\src\start_program.py", line 118, in get_user_input
    PybulletProgram(
  File "~\solo-6dof-motion-platform\src\pybullet_program.py", line 58, in __init__
    PybulletIKClass(robot_environment="pybullet")
  File "~\solo-6dof-motion-platform\src\inverse_kinematics\pybullet_IK.py", line 21, in __init__
    self.data = np.array(self.data)
                ^^^^^^^^^^^^^^^^^^^
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (15361,) + inhomogeneous part.
```

It reports an error like this when I run the "start_project.py" in pycharm. 
>Choice: 2-->1-->1.
>No robot.

**Comment by nayan-pradhan** [comment]
Hi! I am unable to recreate this issue. Can you try from your terminal? You can run the bash script from the`/src` directory:

`bash start_program.sh`

**Comment by SQWung** [comment]
>Thanks！
>It runs normally from linux terminal.
>
